### ISSUE TITLE
where is pattern for searching baidu , weather , etc....

### ISSUE THREAD

**Issue by tommyvio** [littleredhat1997/chatbot-aiml-webqa#2]
help appreciated

**Comment by zhangbincheng1997** [comment]
Find and match the pattern at [`core/crawler/crawl.py`](https://github.com/littleredhat1997/chatbot-aiml-webqa/blob/master/core/crawler/crawl.py), then do the action at [`core/crawler/search.py`](https://github.com/littleredhat1997/chatbot-aiml-webqa/blob/master/core/crawler/search.py).

**Comment by tommyvui** [comment]
hey thank you and I have another question , an attempt to make a very simple, Personal Assistant that understands speech as well as text input and is capable of performing tasks other than conversing. the project is based on AIML and uses pyaiml for using the AIML interpreter in python3. and I got some basic aiml pattern for it and it runs well . and I wanted to add your pattern on it to search baidu,weather etc , but have no idea how , THANK YOU 
[script.txt](https://github.com/littleredhat1997/chatbot-aiml-webqa/files/3084634/script.txt)
